/** Codara package root — public API surface. */

export {
  createCodara,
  createCodaraRuntime,
  DEFAULT_CODARA_MODEL_ALIAS,
  openCodaraSession,
  openLatestCodaraSession,
  type Codara,
  type CodaraAutoMemoryOptions,
  type CodaraRuntimeOptions,
  type CodaraOptions,
  type TeamQuerySummary,
  type TeamQueryMember,
  type TeamQueryJob,
  type TeamQueryDetail,
} from '@codara/index';
export {
  bootstrapAgent,
  type BootstrapAgentOptions,
  type ModelResolver,
  resolveModel,
  type Agent,
  type AgentInput,
  type AgentInvokeConfig,
  type AgentResult,
  type AgentResumeConfig,
  type AgentResumeStreamConfig,
  type AgentRuntimeContext,
  type AgentRuntimeValues,
  type AgentState,
  type AgentStreamConfig,
  type AgentStreamCustomChunk,
  type AgentStreamOutput,
  type AgentType,
  type CreateAgentOptions,
} from '@engine/agent';
export {
  TASK_TOOL_DESCRIPTION,
  TASK_TOOL_NAME,
  createSharedTaskMiddleware,
  createTaskMiddleware,
  type CreateSharedTaskMiddlewareOptions,
  type CreateTaskMiddlewareOptions,
} from '@capability/task';
export {
  createDailySessionFileLogSink,
  createBudgetMiddleware,
  createHILMiddleware,
  createAskUserQuestionMiddleware,
  createLoggingMiddleware,
  createMiddleware,
  createAskUserTool,
  ASK_USER_TOOL_NAME,
  parseAskUserResult,
  createPermissionMiddleware,
  createPermissionRuntime,
  ensurePermissionSettingsFile,
  evaluatePermissionExpression,
  evaluatePermissionToolCall,
  formatPermissionExpression,
  handlePermissionFallbackResume,
  isPermissionPause,
  persistAllowedPermission,
  persistPermissionScope,
  persistPermissionRule,
  resolvePermissionSettingsFile,
  validatePermissionSettings,
  createSummaryMiddleware,
  createSkillsMiddleware,
  type BaseMiddleware,
  type AskUserInput,
  type AskUserOption,
  type AskUserQuestion,
  type AskUserResult,
  type BudgetMiddlewareOptions,
  type ExecutionContextMetadata,
  type AskUserQuestionMiddlewareOptions,
  type HILMiddlewareOptions,
  type HILResumePayload,
  type LoggingMiddlewareOptions,
  type MiddlewareLogRecord,
  type SummarySettings,
  type SummaryOptions,
} from '@engine/pipeline';
export {
  FileCheckpointer,
  InMemoryCheckpointer,
  createAgentFileCheckpointer,
  createAgentMemoryCheckpointer,
  type AgentCheckpoint,
  type AgentCheckpointer,
} from '@engine/checkpoint';
export {
  createCodaraGuidelinesSource,
  type GuidelinesOptions,
  type GuidelinesSource,
} from '@infra/context/instructions/guidelines';
export {
  createCodaraPromptSource,
  type PromptOptions,
  type PromptSource,
} from '@infra/context/instructions/prompt';
export {
  readBaseSystemMessage,
  type BaseSystemMessageBundle,
  type BaseSystemMessageRuntimeData,
} from '@infra/context/system-message';
export {
  createBuiltinTools,
  createFetchTool,
  createSearchTool,
  filterToolsByReferences,
  normalizeToolReferenceName,
  type BuiltinToolOptions,
} from '@engine/tool';
export {
  createCodaraSkillsSource,
  FileSystemSkillStore,
  getDefaultSkillSources,
  loadSkillsRuntimeData,
  type SkillMetadata,
  type SkillStore,
  type SkillsSource,
  type SkillsRuntimeData,
} from '@capability/skill';
export {
  createSession,
  FileSessionStore,
  type CodaraRuntimeEvent,
  type CodaraRuntimeEventListener,
  type Session,
  type SessionStore,
  type SessionState,
  type SessionStatus,
} from '@engine/session';
export {
  ChatModelFactory,
  loadModelRoutingConfig,
  ModelRegistry,
  type ModelInfo,
  type ModelRoutingConfig,
} from '@infra/provider';
export {
  type HookEventType,
  type HookDefinition,
  type HookSource,
  type HookEntry,
  type HookContext,
  type HookOutput,
  type HookInterceptResult,
  type HookNotifyResult,
  type SessionLifecycleHooks,
  type AgentLifecycleHooks,
  type ToolLifecycleHooks,
  type HookRegistry,
  type HookExecutorFactory,
  HOOK_EVENT_TYPES,
  HookRegistryImpl,
  HookPipeline,
  createToolHooksMiddleware,
  createHookExecutor,
} from '@engine/hook';
export {
  createMcpManager,
  createMcpLangChainTools,
  loadMcpConfig,
  McpClient,
  McpConfigSchema,
  namespacedToolName,
  parseNamespacedToolName,
  routeMcpToolCall,
  sanitizeToolName,
  type McpClientInfo,
  type McpClientStatus,
  type McpConfig,
  type McpLocalServerConfig,
  type McpManager,
  type McpRemoteServerConfig,
  type McpServerConfig,
  type McpToolDefinition,
} from '@engine/mcp';
